spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/server_manager
    username: postgres
    password: 3396533965
    driverClassName: org.postgresql.Driver

